[tool.poetry]
name = "python-calculator"
version = "0.1.0"
description = ""
authors = ["ajiang0202@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
kivy = "^2.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
